### ISSUE TITLE
Prevent customer creation race conditions

### ISSUE THREAD

**Issue by ORESoftware** [stripe/stripe-node#476]
There is obviously the classic race condition:

```js
const email = 'foo@example.com';

Promise.all([
  stripe.customers.retrieve(email).then(function(user){
   if(!user){
     return stripe.customers.create(email);
   }
  },
 stripe.customers.retrieve(email).then(function(user){
   if(!user){
     return stripe.customers.create(email);
   }
 }
])
```

this race condition is explained further here:

https://stackoverflow.com/questions/51144576/stripe-create-retrieve-customer-in-one-call/51150846#51150846

how do we mitigate this race condition with the Stripe API? It's unclear if it's possible and if it's not, that's bad.

**Comment by the1mills** [comment]
yeah this is imporant as far as I can tell, can't figure out why this is not addressed in the API

**Comment by brandur-stripe** [comment]
Hi there,

This may be a possibility that you'll have to remedy to some degree on your end. A few common possibilities:

1. If you're storing results to a database, create a unique field there for any particular `customer_email`. That way, when a second conflicting request comes back with a result, it'll error on a unique violation, and you can log that other customer ID to a separate table for eventual cleanup.
2. Establish a locking system for any particular customer email using a shared ephemeral datastore like Redis. A first request locks the value and unlocks it when it finishes, a second request blocks on the lock, and before attempting its own creation, tries to reuse an existing value.

Also see [Remi's great answer to the same question here](https://groups.google.com/a/lists.stripe.com/d/msg/api-discuss/hvqqD6tC7Hs/E1GfaC1yCQAJ).

**Comment by ORESoftware** [comment]
@brandur-stripe  yes, what we could do is create the customer first in our db. but say that customer is not a stripe customer yet, so there is no stripeId for the customer, so then we try to create a stripe account for that customer, but we still have that same race condition.

It has to be atomic on Stripe's end too. Right now you guys aren't doing that.

**Comment by brandur-stripe** [comment]
> @brandur-stripe yes, what we could do is create the customer first in our db, and that creation process would be atomic. but say that customer is not a stripe customer yet, so there is no stripeId for the customer in our db, so then we try to create a stripe account for that customer, but we still have that same race condition.

You don't even need to create the customer first in your DB.

I'll try to be a little more concrete in my suggestions (using Postgres examples, but this will work in almost any relational DB). Say I create a schema like this one with an `email` and `stripe_id`:

``` sql
CREATE TABLE customers (
    id BIGSERIAL,
    email TEXT UNIQUE,
    stripe_id TEXT UNIQUE
);
```

Then I have to requests in flight that are concurrent and contending to be the first customer creation for a particular email. After the first receives a response from Stripe, it'll insert its result in the table:

``` sql
INSERT INTO customers
    (email, stripe_id)
VALUES
    ('foo@example.com', 'cus_123');
```

That works fine. But as the second request resolves and attempts to do the same, it'll get an error like this:

```
ERROR:  duplicate key value violates unique constraint "customers_email_key"
DETAIL:  Key (email)=(foo@example.com) already exists.
```

Even if you make the argument that Stripe should be tracking unique emails for you through the API, you should _still_ be doing something like this as a guarantee that your data is consistent. Personally, I wouldn't trust that any foreign API is bug-free (or that I made a bad assumption about using it and introduced a client-side bug) so it's better to code defensively.

> It should be atomic on Stripe's end too. Right now you guys aren't doing that.

I think there's a slight confusion in terminology here — as long as you're using an idempotency key, the request will be atomic from the user's perspective. We don't enforce uniqueness on customer's email.

> Yes we will have to lock on the user's email when we do creation. That is a big onus on us, Stripe should take care of this. Stripe can have a better level of service if you take care of that for us. That's why we use Stripe, to make it easier for developer integration! :)

Having a basic locking framework in place is something that you'll probably want to have at some point anyway to help avoid lots of application-level concurrent contention. Once you have one, it shouldn't be too much onus to implement locking as I've described.

I'll double check, but I believe that non-unique emails on customer is by design — you can easily imagine a pitfall whereby we error on a non-unique email and that fails more rudimentary integrations that weren't expecting. It might also be useful to track multiple customer entities even if they share an email address. I'll double-check that though.

**Comment by ORESoftware** [comment]
Ok, sure say we have 2 concurrent requests to Stripe, both will succeed. Then we try to insert in our database, and only 1 will succeed, the first one. But then we have an extra Stripe account for that user, because we have two stripe accounts. Why would we want that? Why would stripe want that?

**Comment by remi-stripe** [comment]
@ORESoftware You could also insert in your database before creating the customer on Stripe and then update that record with the corresponding customer id to ensure unicity.

A lot of merchants do have duplicate customers with the same email address for various reasons. We don't have plans to ensure unicity on our end for that reason.

Another hacky approach would be to use an idempotency key based on the customer's email address on customer creation. That way, even if you ran 2 requests in parallel to create a customer, only one would be created since you would use the same idempotency key. That's not the most common usage of idempotency but it would do the trick.

**Comment by brandur-stripe** [comment]
> Another hacky approach would be to use an idempotency key based on the customer's email address on customer creation. That way, even if you ran 2 requests in parallel to create a customer, only one would be created since you would use the same idempotency key. That's not the most common usage of idempotency but it would do the trick.

@remi-stripe I didn't even think of this — clever :)

> Say we have 2 concurrent requests to Stripe, both will succeed. Then we try to insert in our database, and only 1 will succeed, the first one. But then we have an extra Stripe account for that user, because we have two stripe accounts. Why would we want that? Why would stripe want that?

@ORESoftware It's admittedly a little bit of additional development, but a pretty functional solution here is to rescue a conflict in that case, and then insert the second customer record into another table like `stripe_objects_to_clean` with a schema like `(object, stripe_id)`, then have a background process periodically move through the table and issue deletes to Stripe's API.

It's certainly some extra work, but keeping two networked systems in perfect sync generally requires some sort of reconciliation of this kind. Without one, small communication problems of the like of this one will lead to inevitable drift.

> What I am asking stripe to do, is create atomic accounts somehow. Maybe we need another piece besides email.

Yeah, that's an interesting idea. I'm logging a backend issue now for discussion. In the meantime, I'm going to close this issue out as it's not really representative of a bug in the library, but it should still make a handy Google target for people with the same question in the future.

**Comment by ORESoftware** [comment]
hey all thanks yeah using the email address as the idempotency key sounds like a good solution. however, idempotency keys only last 24 hours.  But it should work as far as I can tell.

to be clear I am looking for this:

```js
const email = 'foo@example.com';
Promise.all([
  stripe.customers.retrieveOrCreate(email),
 stripe.customers.retrieveOrCreate(email)
])
```

where `retrieveOrCreate` is atomic - the way to enable that with stripe, since email does not have to be unique, is to have something like a uniqueKey, which would be the email:

```js
const email = 'foo@example.com';
Promise.all([
  stripe.customers.retrieveOrCreate({email, uniqueKey: email}),
  stripe.customers.retrieveOrCreate({email, uniqueKey: email})
])
```
